version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-stretch
    steps:
      - checkout
      - run:
        name: install-yarn
        command: "sudo npm install -g yarn@latest"
      - run:
          name: install-package
          command: "cd client && yarn"
      - run:
          name: testing
          command: "yarn test"
